@URL=http://localhost:3000/users

### Obter pelo ID
GET {{URL}}

### Inserir Usuario
POST {{URL}}
Content-Type: application/json

{
    "name": "Thiago Dal Santo",
    "email": "thiago@thiago.com",
    "password": "123456",
    "phone": "123123123"
}

### Alterar Usuario
PUT {{URL}}
Content-Type: application/json

{
    "name": "Thiago Dal Santo",
    "email": "thiago@thiago.com",
    "password": "123456",
    "phone": "123123123"
}

### Deletar Usuario
DELETE {{URL}}
Content-Type: application/json

{
    "name": "Thiago Dal Santo",
    "email": "thiago@thiago.com",
    "password": "123456",
    "phone": "123123123"
}